# Generated by Django 5.2.8 on 2025-11-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_status',
            field=models.CharField(choices=[('r', 'Read'), ('u', 'Unread')], default='u', max_length=10),
        ),
    ]
